apiVersion: v1
kind: Secret
metadata:
  name: {{ template "steam-ds-starbound.fullname" . }}
  labels:
    app: {{ template "steam-ds-starbound.name" . }}
    chart: {{ template "steam-ds-starbound.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  player-password: {{ default "" .Values.starbound.auth.player.password | b64enc | quote }}
  admin-password: {{ default "" .Values.starbound.auth.admin.password | b64enc | quote }}
  rcon-password: {{ default "" .Values.starbound.rcon.password | b64enc | quote }}
