apiVersion: v1
kind: Service
metadata:
  name: {{ template "steam-ds-starbound.fullname" . }}
  labels:
    app: {{ template "steam-ds-starbound.name" . }}
    chart: {{ template "steam-ds-starbound.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 21025
      targetPort: game
      protocol: TCP
      name: game
    - port: 21026
      targetPort: rcon
      protocol: TCP
      name: rcon
  {{- if .Values.service.externalIP }}
  externalIPs:
    - {{ .Values.service.externalIP | quote }}
  {{- end }}
  selector:
    app: {{ template "steam-ds-starbound.name" . }}
    release: {{ .Release.Name }}
