apiVersion: v1
kind: Secret
metadata:
  name: {{ template "terraria.fullname" . }}
  labels:
    app: {{ template "terraria.name" . }}
    chart: {{ template "terraria.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  server-password: {{ default "" .Values.terraria.cfg.server_password | b64enc | quote }}
