apiVersion: v1
kind: Secret
metadata:
  name: {{ template "factorio-headless.fullname" . }}
  labels:
    app: {{ template "factorio-headless.name" . }}
    chart: {{ template "factorio-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  game-password: {{ default "" .Values.factorio.cfg.game_password | b64enc | quote }}
  rcon-password: {{ default "" .Values.factorio.rcon.password | b64enc | quote }}
  factorio-account-username: {{ default "" .Values.factorio.account.username | b64enc | quote }}
  factorio-account-password: {{ default "" .Values.factorio.account.password | b64enc | quote }}
  factorio-account-token: {{ default "" .Values.factorio.account.token | b64enc | quote }}
