apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio-headless.fullname" . }}
  labels:
    app: {{ template "factorio-headless.name" . }}
    chart: {{ template "factorio-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      name: game
    - port: {{ .Values.factorio.rcon.port }}
      targetPort: rcon
      protocol: TCP
      name: rcon
  {{- if .Values.service.externalIP }}
  externalIPs:
    - {{ .Values.service.externalIP | quote }}
  {{- end }}
  selector:
    app: {{ template "factorio-headless.name" . }}
    release: {{ .Release.Name }}
