{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "steam-ds-csgo.fullname" . }}
  labels:
    app: {{ template "steam-ds-csgo.name" . }}
    chart: {{ template "steam-ds-csgo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
    {{- end }}
  {{- end }}
{{- end }}
