apiVersion: v1
kind: Secret
metadata:
  name: {{ template "steam-ds-csgo.fullname" . }}
  labels:
    app: {{ template "steam-ds-csgo.name" . }}
    chart: {{ template "steam-ds-csgo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  server-password: {{ default "" .Values.csgo.server.password | b64enc | quote }}
  rcon-password: {{ default "" .Values.csgo.rcon.password | b64enc | quote }}
  gslt: {{ default "" .Values.csgo.server.gslt | b64enc | quote }}
  steam-api-key: {{ default "" .Values.csgo.workshop.steamApiKey | b64enc | quote }}
